name: dam_getter
description: "A Score History Dumper for DAM"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.0+1
  http: ^1.2.2
  xml: ^6.5.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.0
  floor: ^1.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.12


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "resource/icon.png"
